platform :ios, '10.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
require_relative '../node_modules/react-native/scripts/react_native_pods'

target 'Wander' do
  config = use_native_modules!
  use_react_native!
  pod 'AKPickerView', :git => 'https://github.com/prscX/AKPickerView.git'
  use_native_modules!
  use_unimodules!

  target 'WanderTests' do
     inherit! :complete
    # Pods for testing
  end
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  #use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
  
end

target 'Wander-tvOS' do
  # Pods for Wander-tvOS

  target 'Wander-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# post_install do |pi|
#   pi.pods_project.targets.each do |t|
#     t.build_configurations.each do |config|
#       config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
#     end
#   end
# end
